[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hod"
version = "0.1.0"
description = "Hierarchical Object Detection Project"
dependencies = [
]

[tool.setuptools.packages.find]
where = ["."]
include = ["hod*"]
